# Generated by Django 5.2.4 on 2025-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='student_photos/default.jpeg', null=True, upload_to='student_photos/'),
        ),
    ]
