# Generated by Django 5.2.4 on 2025-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
