# Generated by Django 5.2.4 on 2025-07-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_current_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_login',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
