# Generated by Django 5.2.4 on 2025-07-19 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('no_of_semesters', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=100)),
                ('staff_phone', models.IntegerField(max_length=10)),
                ('staff_address', models.TextField()),
                ('staff_DOB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('staff_photo', models.ImageField(upload_to='')),
                ('staff_designation', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Login',
            fields=[
                ('staff_log_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(max_length=100)),
                ('no_of_students', models.IntegerField(default=0)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department')),
                ('class_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField(default=1)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
