# Generated by Django 5.2.4 on 2025-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_class_id_staff_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
