# Generated by Django 5.2.4 on 2025-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='credits',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_photo',
            field=models.ImageField(blank=True, default='student_photos/default.jpeg', null=True, upload_to='staff_photos/'),
        ),
    ]
