# Generated by Django 5.2.4 on 2025-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_subjects_credits_alter_staff_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_photo',
            field=models.ImageField(blank=True, default='staff_photos/default.jpeg', null=True, upload_to='staff_photos/'),
        ),
    ]
