# Generated by Django 5.2.4 on 2025-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staff_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_login',
            name='staff_log_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
