# Generated by Django 5.2.4 on 2025-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staff_login_staff_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_login',
            name='staff_log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
