# Generated by Django 5.2.4 on 2025-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_staff_login_staff_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_timetable',
            name='period_1',
        ),
        migrations.RemoveField(
            model_name='class_timetable',
            name='period_2',
        ),
        migrations.RemoveField(
            model_name='class_timetable',
            name='period_3',
        ),
        migrations.RemoveField(
            model_name='class_timetable',
            name='period_4',
        ),
        migrations.RemoveField(
            model_name='class_timetable',
            name='period_5',
        ),
        migrations.RemoveField(
            model_name='class_timetable',
            name='period_6',
        ),
        migrations.AddField(
            model_name='class_timetable',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class_timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
    ]
