# Generated by Django 5.2.4 on 2025-07-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_class_timetable_period_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
    ]
