# Generated by Django 5.2.4 on 2025-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_class_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
