# Generated by Django 5.2.4 on 2025-08-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_attendance_attendance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_ended_date',
            field=models.DateField(default='2025-10-12'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_start_date',
            field=models.DateField(default='2025-08-01'),
        ),
    ]
