# Generated by Django 5.2.4 on 2025-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_attendance_attendance_ended_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='incomplete', max_length=10),
        ),
    ]
