# Generated by Django 5.2.4 on 2025-08-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
