# Generated by Django 5.2.4 on 2025-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_ourpage_imagetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='page_image/'),
        ),
    ]
