# Generated by Django 5.2.4 on 2025-09-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_alter_imagetable_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=1)),
                ('min_percentage', models.FloatField()),
                ('max_percentage', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='grade_obtained',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.grade'),
        ),
    ]
