# Generated by Django 5.2.4 on 2025-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_grade_marks_grade_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='total_marks',
            field=models.FloatField(default=100),
        ),
    ]
