# Generated by Django 5.2.4 on 2025-09-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_alter_marks_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
